name: Deploy to Amazon ECR


on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - 'terraform/**'
      - 'docs/**'
      - 'README.md'
      - 'env.example'
      - '*.svg'
      - 'imgs/**'
env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: "339713077362" 
  
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # --- BUILD FRONTEND ---
    - name: Build and push Frontend
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: cloud-nlp/frontend
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./frontend
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # --- BUILD ORCHESTRATOR ---
    - name: Build and push Orchestrator
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: cloud-nlp/orchestrator
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./orchestrator
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # --- BUILD RAG SERVICE ---
    - name: Build and push RAG Service
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: cloud-nlp/rag-service
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./rag_service
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Force ECS Deployment (Backend)
      run: |
        aws ecs update-service --cluster cloud-nlp-cluster --service cloud-nlp-backend-svc --force-new-deployment --region us-east-1

    - name: Force ECS Deployment (Frontend)
      run: |
        aws ecs update-service --cluster cloud-nlp-cluster --service cloud-nlp-frontend-svc --force-new-deployment --region us-east-1